---
driver:
  name: vagrant
  require_chef_omnibus: true
  customize:
    memory: 512

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
  attributes:
    riak:
      package:
        checksum:
          ubuntu:
            precise: "f2f5af17cce01a769d31517bbdba5a9e1b99e3581bcc4b33e970dbd0ef4140c6"
    riak_cs:
      package:
        checksum:
          ubuntu:
            trusty: "acac19e5c425470642af10d10c33d6a07104cec02cc391046e7f8fed0024e092"
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
  attributes:
    riak:
      package:
        checksum:
          ubuntu:
            precise: "f2f5af17cce01a769d31517bbdba5a9e1b99e3581bcc4b33e970dbd0ef4140c6"
    riak_cs:
      package:
        checksum:
          ubuntu:
            precise: "f21330962c9666822677a2cbf75e394e813feef0638633da37cbdf83d065db5b"
- name: debian-7.2.0
  run_list:
  - recipe[apt]
  attributes:
    riak:
      package:
        checksum:
          debian:
            "7": "3bb6bcc409f51e303978fdb72c8605ac87a502e99bb5b7fda5ecd6af9c343d42"
    riak_cs:
      package:
        checksum:
          debian:
            "7": "dd613b22ab5b0a8910ead83bebd9b6ba59b9093a58fb49b06ae81990700e430d"
- name: centos-6.5
  run_list:
  - recipe[yum-epel]
  attributes:
    riak:
      package:
        checksum:
          centos:
            "6": "5f93a9ed1d7c9326297ebc432d69d1b03e941c057a7cfa37b45138045efdfb4f"
    riak_cs:
      package:
        checksum:
          centos:
            "6": "bb9603a3bee26d9d703c6d73272edbf64bbf17a0d6346c5dc2ba21928019eb08"
- name: centos-5.10
  run_list:
  - recipe[yum-epel]
  attributes:
    riak:
      package:
        checksum:
          centos:
            "5": "33c54fd0daccca7005bf65e152b4893d4fecd0cd70becdcde596fb935d93625e"
    riak_cs:
      package:
        checksum:
          centos:
            "5": "f1991a3dce7915d8f21759d4c07d64dee3779091936a1d2f6ac0955779040c5a"

suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[riak-cs::package]
  - recipe[riak]
  - recipe[riak-cs]
  - recipe[riak-cs::stanchion]
  - recipe[riak-cs-create-admin-user]
  attributes:
    riak_cs:
      package:
        version:
          major: 1
          minor: 5
          incremental: 1
    stanchion:
      package:
        version:
          major: 1
          minor: 5
          incremental: 0
    riak_cs_control:
      package:
        version:
          major: 1
          minor: 0
          incremental: 2
    riak:
      cs_version: "1.5.1"
      package:
        version:
          major: 1
          minor: 4
          incremental: 10
      config:
        riak_kv:
          storage_backend: riak_cs_kv_multi_backend
- name: default14
  run_list:
  - recipe[minitest-handler]
  - recipe[riak-cs::package]
  - recipe[riak]
  - recipe[riak-cs]
  - recipe[riak-cs::stanchion]
  - recipe[riak-cs-create-admin-user]
  attributes:
    riak_cs:
      package:
        version:
          major: 1
          minor: 4
          incremental: 5
    stanchion:
      package:
        version:
          major: 1
          minor: 4
          incremental: 3
    riak_cs_control:
      package:
        version:
          major: 1
          minor: 0
          incremental: 2
    riak:
      cs_version: "1.4.5"
      package:
        version:
          major: 1
          minor: 4
          incremental: 10
      config:
        riak_kv:
          storage_backend: riak_cs_kv_multi_backend
- name: default13
  run_list:
  - recipe[minitest-handler]
  - recipe[riak-cs::package]
  - recipe[riak]
  - recipe[riak-cs]
  - recipe[riak-cs::stanchion]
  - recipe[riak-cs-create-admin-user]
  attributes:
    riak_cs:
      package:
        version:
          major: 1
          minor: 3
          incremental: 1
    stanchion:
      package:
        version:
          major: 1
          minor: 3
          incremental: 1
    riak_cs_control:
      package:
        version:
          major: 1
          minor: 0
          incremental: 0
    riak:
      cs_version: "1.3.1"
      package:
        version:
          major: 1
          minor: 3
          incremental: 2
      config:
        riak_kv:
          storage_backend: riak_cs_kv_multi_backend
- name: enterprise
  run_list:
  - recipe[minitest-handler]
  - recipe[riak-cs::enterprise_package]
  - recipe[riak]
  - recipe[riak-cs]
  - recipe[riak-cs::stanchion]
  - recipe[riak-cs-create-admin-user]
  attributes:
    riak_cs:
      package:
        enterprise_key: <%= (ENV["RIAK_CS_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_CS_ENTERPRISE_KEY"]) %>
        version:
          major: 1
          minor: 4
          incremental: 5
    stanchion:
      package:
        version:
          major: 1
          minor: 4
          incremental: 3
    riak_cs_control:
      package:
        version:
          major: 1
          minor: 0
          incremental: 2
    riak:
      cs_version: "1.4.5"
      package:
        version:
          major: 1
          minor: 4
          incremental: 8
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
      config:
        riak_kv:
          storage_backend: riak_cs_kv_multi_backend
- name: enterprise13
  run_list:
  - recipe[minitest-handler]
  - recipe[riak-cs::enterprise_package]
  - recipe[riak]
  - recipe[riak-cs]
  - recipe[riak-cs::stanchion]
  - recipe[riak-cs-create-admin-user]
  attributes:
    riak_cs:
      package:
        enterprise_key: <%= (ENV["RIAK_CS_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_CS_ENTERPRISE_KEY"]) %>
        version:
          major: 1
          minor: 3
          incremental: 1
    stanchion:
      package:
        version:
          major: 1
          minor: 3
          incremental: 1
    riak_cs_control:
      package:
        version:
          major: 1
          minor: 0
          incremental: 0
    riak:
      cs_version: "1.3.1"
      package:
        version:
          major: 1
          minor: 3
          incremental: 4
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
      config:
        riak_kv:
          storage_backend: riak_cs_kv_multi_backend
