---
driver:
  name: ec2
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_ssh_key_id: <%= ENV["AWS_KEYPAIR_NAME"] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: amazon-2014.03.2
  driver:
    image_id: ami-ed8e9284
    username: ec2-user
    ssh_key: <%= ENV["EC2_SSH_KEY_PATH"] %>
  run_list:
  - recipe[sudo]
  attributes:
    riak:
      package:
        checksum:
          amazon:
            "2014": "5f93a9ed1d7c9326297ebc432d69d1b03e941c057a7cfa37b45138045efdfb4f"
    riak_cs:
      package:
        checksum:
          amazon:
            "2014": "5561c6452f82d0b3d204e30d1943c017bfe2829036c86e2538f296ce0800dde5"
suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[riak-cs::package]
  - recipe[riak]
  - recipe[riak-cs]
  - recipe[riak-cs::stanchion]
  - recipe[riak-cs-create-admin-user]
  attributes:
    riak_cs:
      package:
        version:
          major: 1
          minor: 5
          incremental: 0
    stanchion:
      package:
        version:
          major: 1
          minor: 5
          incremental: 0
    riak_cs_control:
      package:
        version:
          major: 1
          minor: 0
          incremental: 2
    riak:
      cs_version: "1.5.0"
      package:
        version:
          major: 1
          minor: 4
          incremental: 10
      config:
        riak_kv:
          storage_backend: riak_cs_kv_multi_backend
- name: enterprise
  run_list:
  - recipe[minitest-handler]
  - recipe[riak-cs::enterprise_package]
  - recipe[riak]
  - recipe[riak-cs]
  - recipe[riak-cs::stanchion]
  - recipe[riak-cs-create-admin-user]
  attributes:
    riak_cs:
      package:
        enterprise_key: <%= (ENV["RIAK_CS_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_CS_ENTERPRISE_KEY"]) %>
        version:
          major: 1
          minor: 5
          incremental: 0
    stanchion:
      package:
        version:
          major: 1
          minor: 5
          incremental: 0
    riak_cs_control:
      package:
        version:
          major: 1
          minor: 0
          incremental: 2
    riak:
      package:
        version:
          major: 1
          minor: 4
          incremental: 10
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
      config:
        riak_kv:
          storage_backend: riak_cs_kv_multi_backend
