---

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: amazon-2014.03.2
  driver:
    name: ec2
    image_id: ami-7c807d14
    username: ec2-user
    ssh_key: <%= ENV["EC2_SSH_KEY_PATH"] %>
  run_list:
  - recipe[sudo]
  attributes:
    riak:
      package:
        checksum:
          amazon:
            "2014": "5f93a9ed1d7c9326297ebc432d69d1b03e941c057a7cfa37b45138045efdfb4f"
    riak_cs:
      package:
        checksum:
          amazon:
            "2014": "108d9cb5487a6394e311e51153d0ab505962e14777c764da50c10c6084380266"
- name: ubuntu-14-04-x64
  driver:
    name: digitalocean
  run_list:
  - recipe[apt]
- name: ubuntu-12-04-x64
  driver:
    name: digitalocean
  run_list:
  - recipe[apt]
- name: debian-7-0-x64
  driver:
    name: digitalocean
  run_list:
  - recipe[apt]
- name: centos-6-5-x64
  driver:
    name: digitalocean
  run_list:
  - recipe[sudo]
  - recipe[yum-epel]
- name: centos-5-8-x64
  driver:
    name: digitalocean
  run_list:
  - recipe[sudo]
  - recipe[yum-epel]
suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[riak-cs::package]
  - recipe[riak]
  - recipe[riak-cs]
  - recipe[riak-cs::stanchion]
  - recipe[riak-cs-create-admin-user]
  attributes:
    riak_cs:
      package:
        version:
          major: 1
          minor: 5
          incremental: 2
    stanchion:
      package:
        version:
          major: 1
          minor: 5
          incremental: 0
    riak_cs_control:
      package:
        version:
          major: 1
          minor: 0
          incremental: 2
    riak:
      cs_version: "1.5.2"
      package:
        version:
          major: 1
          minor: 4
          incremental: 10
      config:
        riak_kv:
          storage_backend: riak_cs_kv_multi_backend
- name: enterprise
  run_list:
  - recipe[minitest-handler]
  - recipe[riak-cs::enterprise_package]
  - recipe[riak]
  - recipe[riak-cs]
  - recipe[riak-cs::stanchion]
  - recipe[riak-cs-create-admin-user]
  attributes:
    riak_cs:
      package:
        enterprise_key: <%= (ENV["RIAK_CS_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_CS_ENTERPRISE_KEY"]) %>
        version:
          major: 1
          minor: 5
          incremental: 2
    stanchion:
      package:
        version:
          major: 1
          minor: 5
          incremental: 0
    riak_cs_control:
      package:
        version:
          major: 1
          minor: 0
          incremental: 2
    riak:
      package:
        version:
          major: 1
          minor: 4
          incremental: 10
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
      config:
        riak_kv:
          storage_backend: riak_cs_kv_multi_backend
